spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: user_21
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
server:
  port: 8080
  servlet:
    context-path: /cansr
